# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 12 Dec 2014 19:08:02 +0000
*               @ALL          0
*               @user         8
